### ISSUE TITLE
Use Buffer#indexOf if available

### ISSUE THREAD

**Issue by ronkorving** [mscdex/streamsearch#2] opened 2015-07-10 07:41 UTC
I wanted to point your attention to [Buffer.indexOf](https://github.com/nodejs/io.js/commit/78581c8d902f2ed32712b342091d89016030e4ba) which has the potential to speed up this library, possibly dramatically. If the API exists (depending on Node version I guess), it may make a lot of sense to use it.

PS: I'm using Dicer for multipart stream parsing and streamsearch shows up in my CPU profile more than may be necessary.

PS2: Amusing to see you actually reviewed that PR by Trevor :)

**Comment by mscdex** [comment] 2015-07-10 14:39
The issue is that `buffer.indexOf` isn't really optimal yet. I think Trevor was going to look into various string matching algorithms, but that effort may be stalled. This module uses BMH for string matching, so I think it *should* currently be faster than `buffer.indexOf`.

**Comment by ronkorving** [comment] 2015-07-11 06:00
That should be the goal though. @trevnorris are there any updates on this?

**Comment by trevnorris** [comment] 2015-07-11 06:26
`indexOf()` is freaking slow. Haven't taken the time to fix that yet, but I'll try to do that soon.

**Comment by ronkorving** [comment] 2015-07-11 06:28
Thanks a lot, @trevnorris. It's really appreciated.

**Comment by ronkorving** [comment] 2015-10-08 05:05
This just landed: https://github.com/nodejs/node/commit/a18dd7b7882ca955075ad977a5e7838c792bb76f

**Comment by mscdex** [comment] 2015-10-08 14:54
This module can't really use `buffer.indexOf()` since it has to store algorithm-specific state (it's searching a stream instead of a single block of data). `buffer.indexOf()` does not expose its internal state anyway and it does not accept internal state to use for future invocations, it's meant as a one-shot search kind of thing.

Having `.indexOf()` for streams somehow in core would be neat, but I doubt something like that would ever be accepted.

**Comment by mscdex** [comment] 2021-12-06 04:22
Closing this for now as nothing has changed and there is nothing actionable here. Even if there was some way to make use of it with streams (or even if node had a stream-compatible `indexOf()`), I'm still not entirely convinced that reaching into C++ to perform the search wouldn't cause a noticeable performance hit.

**Closed by mscdex** 2021-12-06 04:22 UTC

**Comment by ronkorving** [comment] 2021-12-06 07:21
@mscdex Long time no see ;)
By all means close this, I don't think this issue impacts my life anymore. If it did, I guess I would have serious problems.

**Comment by davidje13** [comment] 2025-11-09 00:48
Many years have passed and Node.js' internals have moved on, so I've had a go at implementing this suggestion in an embedded fork I'm using in one of my own projects, and it (quite surprisingly) turns out to be significantly faster in almost all cases.

I say surprisingly because calling `indexOf` multiple times means Node.js has to recalculate things like the `occ` table, whereas the existing implementation can calculate it once and re-use it across chunks and occurrences of the needle.

But the results really are very pronounced:

| Test Needle              | adapted streamsearch (100kB data) | streamsearch@1.1.0 (100kB data) | Buffer.indexOf (100kB data) | adapted streamsearch (2kB batches) | streamsearch@1.1.0 (2kB batches) |
| ------------------------ | ------------ | ------------------ | -------------- | ---------------------- | ---------------------------- |
| \r\n                     |        4.0µs |            169.3µs |        * 3.9µs |                * 6.8µs |                      200.9µs |
| \r\n--sep                |        4.0µs |             95.4µs |        * 3.8µs |                * 6.9µs |                       97.8µs |
| realistic                |        4.5µs |             15.7µs |        * 4.5µs |                * 8.0µs |                       21.0µs |
| repetitive prefixed      |        5.3µs |             13.8µs |        * 5.3µs |                * 8.3µs |                       26.0µs |
| long repetitive prefixed |        6.5µs |             36.6µs |        * 6.2µs |               * 17.0µs |                      157.4µs |
| repetitive suffixed      |        4.6µs |             15.2µs |        * 4.5µs |               * 10.0µs |                       24.9µs |
| long repetitive suffixed |       14.0µs |             33.6µs |       * 13.6µs |               * 76.7µs |                      181.5µs |

The "adapted" column is using `Buffer.indexOf` as much as possible, along with a few other optimisations around how the lookbehind is handled by offloading some of the filtering and comparisons to Buffer methods. You can see the full (heavily modified) source here: https://github.com/davidje13/web-listener/blob/main/src/forks/streamsearch/sbmh.mts

The left 3 columns of results are when running in an artificial world where there is only a single 100kB chunk. A "dumb" `Buffer.indexOf`-loop implementation is shown here for comparison. The right 2 columns are a more realistic scenario where the same data is split into 2kB chunks, so "lookbehind" handling is required.

The above table is from running on a Mac running Node.js 24.

On linux (on a Pi 5 running Node.js 22), the results are similar:

| Test Needle              | adapted streamsearch (100kB data) | streamsearch@1.1.0 (100kB data) | Buffer.indexOf (100kB data) | adapted streamsearch (2kB batches) | streamsearch@1.1.0 (2kB batches) |
| ------------------------ | ------------ | ------------------ | -------------- | ---------------------- | ---------------------------- |
| \r\n                     |       12.9µs |            623.5µs |       * 10.5µs |               * 24.4µs |                      632.6µs |
| \r\n--sep                |       10.9µs |            180.5µs |       * 10.7µs |               * 24.6µs |                      184.7µs |
| realistic                |       11.5µs |             27.0µs |       * 11.3µs |               * 26.8µs |                       37.4µs |
| repetitive prefixed      |       11.4µs |             29.9µs |       * 11.0µs |               * 28.9µs |                       47.8µs |
| long repetitive prefixed |       19.1µs |            120.1µs |       * 18.0µs |               * 61.1µs |                      287.6µs |
| repetitive suffixed      |       12.9µs |             28.2µs |       * 12.4µs |               * 45.1µs |                       47.5µs |
| long repetitive suffixed |       64.8µs |            141.0µs |       * 64.2µs |              * 255.9µs |                      296.8µs |

The tests use randomised data so the numbers fluctuate a little. The one case where I've _sometimes_ seen the current implementation out-perform the adapted version is when the needle is a long list of the same character followed by a different character (the last entry in the table - the test uses 1000 dashes followed by a dot), where streamsearch@1.1.0 is occasionally 2-3x faster depending on the random haystack data.

---

Methodology:

This experiment used a 100kB input containing 9 needles at fixed offsets (several chosen to cross chunk boundaries). The other data is random, and includes a random quantity of partial needle matches. You can find the (quite messy) code behind it here: https://github.com/davidje13/web-listener/blob/main/performance/StreamSearch.test.mts
